### ISSUE TITLE
Rhoooo : "UK" return everything except ... United Kindom

### ISSUE THREAD

**Issue by odadoun** [tjbtjbtjb/CoCoA#5]
This is a Brexit stuff ?? :-)
/Users/dadoun/Programs/Python/CoCoA/cocoa/geo.py:171: UserWarning: Caution. More than one country match the key "UK" : ['Ukraine, ', 'Latvia, ', 'Uganda, ', 'Albania, ', 'Japan, ', 'Thailand, ', 'Tuvalu, ', 'Indonesia, ', 'Canada, ', 'Croatia, ', 'Philippines, ', 'Slovenia, ', 'Tanzania, United Republic of, ', 'Algeria, ', "Korea, Democratic People's Republic of, ", 'Korea, Republic of, ', 'Russian Federation, ', 'Bhutan, ', 'Micronesia, Federated States of, ', 'Iraq, ', 'Marshall Islands, ', 'Saudi Arabia, ', 'Dominica, ', 'Egypt, ', 'Cambodia, ', 'Morocco, ', 'Turkey, '], using first one.

  ', using first one.\n')

**Comment by tjbtjbtjb** [comment]
The standard iso2 name for United Kingdom is GB. UK doesn't exist, and the most probable name looking like "UK" is 
'Ukraine'.
A warning is given by the GeoManager instance, but 'Ukraine' is returned. 

I don't think it would be a good feature to enforce UK to be interpreted as GB. That's why I'm closing this issue.
